### ISSUE TITLE
Plugin Status

### ISSUE THREAD

**Issue by dkanada** [moritz31/jellyfin-plugin-oidcauth#1]
How is this repository coming along? We've actually wanted to add an official OIDC plugin for some time but no one has done so yet. I figured it would need a few frontend changes to work properly, is that the case?

**Comment by moritz31** [comment]
Hey @dkanada i've started the plugin because i thought it  was a cool idea and i would have loved to contribute to jellyfin.
The Problem we identified that a plugin alone isn't working but jellyfin need to support oauth which would be a bigger challange.
